// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVVPSZ1rpoNO2DvTRbm4KHtA7HfFqwvs0',
    appId: '1:863287440114:web:337de396afdd12e500d66b',
    messagingSenderId: '863287440114',
    projectId: 'flutter-firebase-a3152',
    authDomain: 'flutter-firebase-a3152.firebaseapp.com',
    storageBucket: 'flutter-firebase-a3152.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXH8WU4n5rj1osW34Uan5womGZ8Ox2HRw',
    appId: '1:863287440114:android:68c215f025ee93b200d66b',
    messagingSenderId: '863287440114',
    projectId: 'flutter-firebase-a3152',
    storageBucket: 'flutter-firebase-a3152.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoriAWXVhPmtHeRMZYg0fdAqj2GljXLI',
    appId: '1:863287440114:ios:28f0e31e60a6cf5400d66b',
    messagingSenderId: '863287440114',
    projectId: 'flutter-firebase-a3152',
    storageBucket: 'flutter-firebase-a3152.appspot.com',
    iosClientId: '863287440114-59d4l4qn02l40lfa32qvcomfsqokprlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoriAWXVhPmtHeRMZYg0fdAqj2GljXLI',
    appId: '1:863287440114:ios:28f0e31e60a6cf5400d66b',
    messagingSenderId: '863287440114',
    projectId: 'flutter-firebase-a3152',
    storageBucket: 'flutter-firebase-a3152.appspot.com',
    iosClientId: '863287440114-59d4l4qn02l40lfa32qvcomfsqokprlu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myNewsApp',
  );
}
